apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi

resources:
- ../../base/serviceaccounts/moc-nfs-democratic-csi-controller-sa/
- ../../base/serviceaccounts/moc-nfs-democratic-csi-node-sa/
- ../../base/deployments/moc-nfs-democratic-csi-controller/
- ../../base/daemonsets/moc-nfs-democratic-csi-node/
- ../../base/secrets/node-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi/
- ../../base/secrets/node-stage-secret-moc-nfs-csi-moc-nfs-democratic-csi/
- ../../base/secrets/provisioner-secret-moc-nfs-csi-moc-nfs-democratic-csi/
- ../../base/secrets/controller-expand-secret-moc-nfs-csi-moc-nfs-democratic-csi/
- ../../base/secrets/controller-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi/
